version: '3.8'
services:
  selenium:
    image: selenium/standalone-firefox:4.18.1-20240224
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - mynetwork
    ports:
      - 4444:4444
      - 7900:7900

  db:
    image: postgres:13
    networks:
      - mynetwork
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432

  mywebsite:
    build:
      context: .
      dockerfile: Dockerfile
    image: mywebsite:tag
    networks:
      - mynetwork
    ports:
      - 8000:8000
    environment:
      - API_KEY=${API_KEY}
      - SELENIUM_SERVER_URL=${SELENIUM_SERVER_URL}
      - MYWEBSITE_URL=${MYWEBSITE_URL}
    depends_on:
      - db
      - selenium
    volumes:
    - .:/website_wsl

networks:
  mynetwork:

volumes:
  postgres_data:
