# Generated by Django 5.0.2 on 2024-05-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('youtubers', '0006_youtuber_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='youtubers.youtuber'),
        ),
    ]
