# Generated by Django 5.0.1 on 2024-01-09 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Youtuber",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("channel_id", models.CharField(max_length=255)),
                ("channel_title", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("channel_description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("youtube", models.CharField(blank=True, max_length=255, null=True)),
                ("twitch", models.CharField(blank=True, max_length=255, null=True)),
                ("telegram", models.CharField(blank=True, max_length=255, null=True)),
                ("instagram", models.CharField(blank=True, max_length=255, null=True)),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
                ("slug_name", models.SlugField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("slug_name", models.SlugField(blank=True, max_length=255, null=True)),
                (
                    "youtuber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="youtubers.youtuber",
                    ),
                ),
            ],
        ),
    ]
