# Generated by Django 5.0.2 on 2024-03-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_youtuber_tags'),
        ('youtubers', '0005_alter_comment_user'),
    ]

    operations = [
    ]
