name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - '*'

jobs:
  run_pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.7.0"]
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      SELENIUM_SERVER_URL: ${{ secrets.SELENIUM_SERVER_URL }}
      MYWEBSITE_URL: ${{ secrets.MYWEBSITE_URL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and run Docker containers
        run: docker-compose up -d

      - name: Execute func tests
        run: docker-compose exec -T mywebsite /bin/bash -c "export SELENIUM_TESTS=1 && poetry run pytest -v --reruns 5"

      - name: Run users unit tests
        run: docker-compose exec -T mywebsite poetry run python youtube_base/manage.py test users

      - name: Run youtubers unit tests
        run: docker-compose exec -T mywebsite poetry run python youtube_base/manage.py test youtubers
